<h1 style="color: black;">Projet : Préparation et Analyse de Données Financières</h1>

<h2 style="color: black;">Contexte</h2>
Ce mini-projet a pour but de maîtriser la manipulation de données financières historiques en utilisant Python. Nous allons nous concentrer sur trois géants de la tech (GAFAM) : <strong>Microsoft</strong>, <strong>Google</strong> et <strong>Amazon</strong>.

<h2 style="color: black;">Objectifs du Défi</h2>
L'objectif principal est d'importer, de structurer et d'inspecter les données boursières sur la période allant de <strong>2022 à 2024</strong>.

Les étapes clés de ce notebook sont :
1.  <strong>Importation :</strong> Récupérer les données pour les tickers `MSFT`, `GOOGL`, et `AMZN`.
2.  <strong>Structuration :</strong> Créer trois DataFrames distincts pour chaque entreprise.
3.  <strong>Exploration :</strong>
    * Afficher les 10 premières lignes (aperçu).
    * Compter les valeurs manquantes (nettoyage).
    * Décrire les statistiques des colonnes.

<hr>
<strong>Outils utilisés :</strong> Python, Pandas, Jupyter Notebook.

In [4]:
# 1. Définition des paramètres
start = "2022-01-01"
end = "2024-12-31"
tickers = ['MSFT', 'GOOGL', 'AMZN']

In [5]:
# 2. Importation des librairies
!pip install yfinance
import yfinance as yf
import pandas as pd

Requirement already satisfied: yfinance in c:\users\volka\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\volka\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\volka\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\volka\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.1.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\volka\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\volka\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in c:\users\volka\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\volka\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\volka\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\volka\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\volka\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\volka\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\volka\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (1.26.20)

In [8]:
# 3. Téléchargement des données
data = yf.download(tickers, start=start, end=end)
# 4. Affichage
data.head()

[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AMZN       GOOGL        MSFT        AMZN       GOOGL
Date
2022-01-03  170.404495  143.904190  323.898407  170.703506  144.757242
2022-01-04  167.522003  143.316635  318.344452  171.399994  145.386491
2022-01-05  164.356995  136.741821  306.123871  167.126495  143.415897
2022-01-06  163.253998  136.714523  303.704895  164.800003  138.890587
2022-01-07  162.554001  135.989502  303.859680  165.243500  137.410270

Price                          Low                                Open  \
Ticker            MSFT        AMZN       GOOGL        MSFT        AMZN
Date
2022-01-03  327.043052  166.160507  142.635274  319.089518  167.550003
2022-01-04  324.333792  166.349503  142.638758  315.548123  170.438004
2022-01-05  315.499751  164.356995  136.655483  305.736844  166.882996
2022-01-06  308.368651  161.936996  135.534444  301.392358  163.450500
2022-01-07  306.239925  162.031006  134.748376  300.037717  163.839005

Price                                 Volume
Ticker           GOOGL        MSFT      AMZN     GOOGL      MSFT
Date
2022-01-03  143.967206  324.478963  63520000  28646000  28865100
2022-01-04  144.305653  323.975762  70726000  28400000  32674300
2022-01-05  143.336995  315.296537  64302000  54618000  40054300
2022-01-06  135.971147  302.998549  51958000  37348000  39646100
2022-01-07  137.109534  303.966100  46606000  29760000  32720000

In [12]:
#4 Regroupons les tickers:
data_group = yf.download(tickers, start=start, end=end, group_by ="tickers")
data_group.head()

[*********************100%***********************]  3 of 3 completed

Ticker           GOOGL                                                \
Price             Open        High         Low       Close    Volume
Date
2022-01-03  143.967206  144.757242  142.635274  143.904190  28646000
2022-01-04  144.305653  145.386491  142.638758  143.316635  28400000
2022-01-05  143.336995  143.415897  136.655483  136.741821  54618000
2022-01-06  135.971147  138.890587  135.534444  136.714523  37348000
2022-01-07  137.109534  137.410270  134.748376  135.989502  29760000

Ticker            AMZN                                                \
Price             Open        High         Low       Close    Volume
Date
2022-01-03  167.550003  170.703506  166.160507  170.404495  63520000
2022-01-04  170.438004  171.399994  166.349503  167.522003  70726000
2022-01-05  166.882996  167.126495  164.356995  164.356995  64302000
2022-01-06  163.450500  164.800003  161.936996  163.253998  51958000
2022-01-07  163.839005  165.243500  162.031006  162.554001  46606000

Ticker            MSFT
Price             Open        High         Low       Close    Volume
Date
2022-01-03  324.478963  327.043052  319.089518  323.898407  28865100
2022-01-04  323.975762  324.333792  315.548123  318.344452  32674300
2022-01-05  315.296537  315.499751  305.736844  306.123871  40054300
2022-01-06  302.998549  308.368651  301.392358  303.704895  39646100
2022-01-07  303.966100  306.239925  300.037717  303.859680  32720000

In [16]:
# Créer trois DataFrames distincts pour chaque entreprise
MSFT = data_group["MSFT"]
AMZN = data_group["AMZN"]
GOOGL = data_group["GOOGL"]

In [17]:
# Afficher les 10 premières lignes "MSFT"
MSFT.head(10)

Price             Open        High         Low       Close    Volume
Date
2022-01-03  324.478963  327.043052  319.089518  323.898407  28865100
2022-01-04  323.975762  324.333792  315.548123  318.344452  32674300
2022-01-05  315.296537  315.499751  305.736844  306.123871  40054300
2022-01-06  302.998549  308.368651  301.392358  303.704895  39646100
2022-01-07  303.966100  306.239925  300.037717  303.859680  32720000
2022-01-10  299.457230  304.517700  294.812844  304.082275  44289500
2022-01-11  303.221088  306.346361  299.844233  304.769226  29386800
2022-01-12  309.307185  312.925935  306.801119  307.952545  34372200
2022-01-13  310.081319  310.478032  294.145226  294.919281  45366000
2022-01-14  294.387156  300.744184  293.903364  300.144287  39846400

In [18]:
# Afficher les 10 premières lignes "AMZN"
AMZN.head(10)

Price             Open        High         Low       Close    Volume
Date
2022-01-03  167.550003  170.703506  166.160507  170.404495  63520000
2022-01-04  170.438004  171.399994  166.349503  167.522003  70726000
2022-01-05  166.882996  167.126495  164.356995  164.356995  64302000
2022-01-06  163.450500  164.800003  161.936996  163.253998  51958000
2022-01-07  163.839005  165.243500  162.031006  162.554001  46606000
2022-01-10  160.585495  161.661499  156.304504  161.485992  87798000
2022-01-11  161.500000  166.350006  160.701508  165.362000  62806000
2022-01-12  166.574997  166.878006  164.417007  165.207001  50030000
2022-01-13  165.250504  166.221497  161.091003  161.214005  52188000
2022-01-14  160.149994  162.250000  159.800507  162.138000  45974000

In [19]:
# Afficher les 10 premières lignes "GOOGL"
GOOGL.head(10)

Price             Open        High         Low       Close    Volume
Date
2022-01-03  143.967206  144.757242  142.635274  143.904190  28646000
2022-01-04  144.305653  145.386491  142.638758  143.316635  28400000
2022-01-05  143.336995  143.415897  136.655483  136.741821  54618000
2022-01-06  135.971147  138.890587  135.534444  136.714523  37348000
2022-01-07  137.109534  137.410270  134.748376  135.989502  29760000
2022-01-10  134.065034  137.778477  132.165886  137.629593  44408000
2022-01-11  136.972102  139.164537  135.667461  138.688126  28730000
2022-01-12  140.091505  141.538579  139.639430  140.369904  26108000
2022-01-13  140.478572  141.778761  137.371055  137.547729  31436000
2022-01-14  136.051044  139.686585  135.971158  138.434540  29662000

In [20]:
# Compter les valeurs manquantes "GOOGL"
GOOGL.isnull().sum()

Price
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [21]:
# Compter les valeurs manquantes "AMZN"
AMZN.isnull().sum()

Price
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [22]:
# Compter les valeurs manquantes "MSFT"
MSFT.isnull().sum()

Price
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [23]:
# Décrire les statistiques des colonnes "GOOGL"
GOOGL.describe()

Price        Open        High         Low       Close        Volume
count  752.000000  752.000000  752.000000  752.000000  7.520000e+02
mean   131.438554  133.032774  129.984162  131.510347  3.166252e+07
std     27.207998   27.313742   27.052952   27.179463  1.310293e+07
min     84.759574   85.871184   82.715030   82.804359  9.701400e+06
25%    109.172628  111.175616  107.289353  109.369755  2.321690e+07
50%    130.478149  132.002623  128.906032  130.479134  2.834020e+07
75%    150.135622  152.507652  149.361478  150.481243  3.658662e+07
max    196.480486  200.634216  194.219337  195.892792  1.232000e+08

In [24]:
# Décrire les statistiques des colonnes "AMZN"
AMZN.describe()

Price        Open        High         Low       Close        Volume
count  752.000000  752.000000  752.000000  752.000000  7.520000e+02
mean   144.022670  145.870071  142.063406  144.017345  5.865235e+07
std     35.125857   35.202713   34.988264   35.128885  2.874809e+07
min     82.800003   83.480003   81.430000   81.820000  1.500750e+07
25%    114.770000  116.917500  113.145000  115.007502  4.072778e+07
50%    140.709999  143.275002  138.784752  140.187996  5.216875e+07
75%    175.579994  177.507500  173.704998  175.360004  6.858920e+07
max    232.389999  233.000000  228.009995  232.929993  2.726620e+08

In [25]:
# Décrire les statistiques des colonnes "MSFT"
MSFT.describe()

Price        Open        High         Low       Close        Volume
count  752.000000  752.000000  752.000000  752.000000  7.520000e+02
mean   328.391477  331.568088  324.994974  328.394328  2.650254e+07
std     71.086701   71.060996   70.926294   71.057791  1.091259e+07
min    211.872987  214.658329  207.860489  208.659073  7.164500e+06
25%    264.180751  268.036505  260.792896  264.615562  1.940788e+07
50%    319.848521  323.693510  316.400066  319.480576  2.410155e+07
75%    404.945617  408.311001  401.430250  404.759064  3.041355e+07
max    461.821761  463.156798  459.309929  462.375549  9.042890e+07